### ISSUE TITLE
 Bad conditionals make Backup Domain Controllers evaluate Member Server rules rather than Domain Controller rules

### ISSUE THREAD

**Issue by mfann-or** [ansible-lockdown/Windows-2019-STIG#23]
[Here](https://github.com/ansible-lockdown/Windows-2019-STIG/blob/7428e8d5eff0a4151dc93ad3925d12d2e8c195d1/tasks/cat1.yml#L38) is one example of many where the role needs to update this conditional to account for Backup Domain Controllers.

Issue:

Bad conditionals make Backup Domain Controllers evaluate Member Server rules rather than Domain Controller rules

Possible Solutions:

1. The conditional could use the same Ansible fact, but change the logic.
``` yaml
when:
  - "'domain controller' in ansible_windows_domain_role"
```

2. The conditional could use a different Ansible fact that is the same across Domain Controller types.
```yaml
when:
  - ansible_os_product_type == "domain_controller"
```

**Comment by frederickw082922** [comment]
Thank you @MikeCantCode appreciate you taking the time to submit your PR. Unfortunately, we closed your Issue due to keeping PDC vs Member Server vs Standonle testing pipeline baseline for clients. We have noted the secondary domain controller behavior in our backlog. When the secondary controller baseline gets addressed, we will make the change to all of DC controls. Thank you for your patience and understanding.
